[package]
name = "ping"
version = "0.1.0"
edition = "2021"

[dependencies]
hubris-task-slots = { version = "0.1.0", path = "../../sys/task-slots" }
userlib = {workspace = true, features = ["no-panic"]}
